//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workout_Programs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Implement INotifyPropertyChanged to send aleart when change has been made.
    /// Declare the different properties in the database. 
    /// </summary>
    public partial class WorkoutDetail : INotifyPropertyChanged
    {
        private string iD;
        private string workout1;
        private string sets_Reps1;
        private string weight1;
        private string workout2;
        private string sets_Reps2;
        private string weight2;
        private string workout3;
        private string sets_Reps3;
        private string weight3;

        public string ID
        {
            get => iD;
            set
            {
                iD = value;
                OnPropertyChanged(nameof(iD));
            }
        }
        public string Workout1
        {
            get => workout1;
            set
            {
                workout1 = value;
                OnPropertyChanged(nameof(Workout1));
            }
        }
        public string Sets_Reps1
        {
            get => sets_Reps1;
            set
            {
                sets_Reps1 = value;
                OnPropertyChanged(nameof(Sets_Reps1));
            }
        }

        public string Weight1
        {
            get => weight1;
            set
            {
                weight1 = value;
                OnPropertyChanged(nameof(Weight1));
            }
        }
        public string Workout2
        {
            get => workout2;
            set
            {
                workout2 = value;
                OnPropertyChanged(nameof(Workout2));
            }
        }
        public string Sets_Reps2
        {
            get => sets_Reps2;
            set
            {
                sets_Reps2 = value;
                OnPropertyChanged(nameof(Sets_Reps2));
            }
        }
        public string Weight2
        {
            get => weight2; 
            set
            { 
                weight2 = value;
                OnPropertyChanged(nameof(Weight2));
            }
        }
        public string Workout3
        {
            get => workout3; 
            set
            {
                workout3 = value;
                OnPropertyChanged(nameof(Workout3));
            }
        }
        public string Sets_Reps3
        {
            get => sets_Reps3; 
            set
            { 
                sets_Reps3 = value;
                OnPropertyChanged(nameof(Sets_Reps3));
            }
        }
        public string Weight3
        {
            get => weight3; 
            set
            { 
                weight3 = value;
                OnPropertyChanged(nameof(Weight3));
            }
        }


        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
